
@baseUrl = http://localhost:8080
@userId = 2

### 1. Создать новую задачу
# @name createTask1
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Купить молоко",
  "status": "OPEN",
  "createdBy": {{userId}}
}

### 2. Создать ещё одну задачу
# @name createTask2
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Сделать лабораторную",
  "status": "IN_PROGRESS",
  "createdBy": {{userId}}
}

### 3. Создать задачу с игнорируемыми полями
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "id": 999,
  "title": "Протестировать игнорирование полей",
  "status": "OPEN",
  "createdBy": 2,
  "createdAt": "2000-01-01T00:00:00"
}

### 4. Получить задачу по идентификатору (существующая)
# @name getTask1
GET {{baseUrl}}/tasks/{{createTask1.response.body.id}}

### 5. Получить задачу по идентификатору (несуществующая)
GET {{baseUrl}}/tasks/999

### 6. Получить все задачи пользователя (без дат)
GET {{baseUrl}}/tasks?userId={{userId}}

### 7. Получить задачи в диапазоне дат
GET {{baseUrl}}/tasks?from=2026-01-01T00:00:00&to=2026-12-31T23:59:59&userId={{userId}}

### 8. Обновить задачу
PUT {{baseUrl}}/tasks/{{createTask1.response.body.id}}
Content-Type: application/json

{
  "title": "Купить молоко",
  "status": "DONE",
  "createdBy": {{userId}}
}

### 9. Обновить задачу (игнорирование id из тела)
PUT {{baseUrl}}/tasks/{{createTask2.response.body.id}}
Content-Type: application/json

{
  "id": 999,
  "title": "Сделать лабораторную (обновлено)",
  "status": "DONE",
  "createdBy": {{userId}}
}

### 10. Обновить несуществующую задачу
PUT {{baseUrl}}/tasks/999
Content-Type: application/json

{
  "title": "Несуществующая задача",
  "status": "OPEN",
  "createdBy": {{userId}}
}

### 11. Подсчитать активные задачи пользователя
GET {{baseUrl}}/tasks/active/count?userId={{userId}}

### 12. Удалить задачу
DELETE {{baseUrl}}/tasks/{{createTask1.response.body.id}}

### 13. Удалить несуществующую задачу
DELETE {{baseUrl}}/tasks/999

### 14. Проверить, что задача удалена
GET {{baseUrl}}/tasks/{{createTask1.response.body.id}}