
@baseUrl = http://localhost:8080
@userId = 2

### Создать задачу
# @name createTask1
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Купить молоко",
  "status": "OPEN",
  "createdBy": {{userId}}
}

### Создать задачу
# @name createTask2
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Сделать лабораторную",
  "status": "IN_PROGRESS",
  "createdBy": {{userId}}
}

### Создать задачу
# @name createTask3
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "id": 999,
  "title": "Протестировать игнорирование полей",
  "status": "OPEN",
  "createdBy": 2,
  "createdAt": "2000-01-01T00:00:00"
}

### Получить задачу по идентификатору
# @name getTask1
GET {{baseUrl}}/tasks/{{createTask1.response.body.id}}

GET {{baseUrl}}/tasks/999

### Получить все задачи пользователя 
GET {{baseUrl}}/tasks?userId={{userId}}

GET {{baseUrl}}/tasks?from=2026-01-01T00:00:00&to=2026-12-31T23:59:59&userId={{userId}}

### Обновить задачу
PUT {{baseUrl}}/tasks/{{createTask1.response.body.id}}
Content-Type: application/json

{
  "title": "Купить молоко",
  "status": "DONE",
  "createdBy": {{userId}}
}

### Обновить задачу 
PUT {{baseUrl}}/tasks/{{createTask2.response.body.id}}
Content-Type: application/json

{
  "id": 999,
  "title": "Сделать лабораторную (обновлено)",
  "status": "DONE",
  "createdBy": {{userId}}
}

### Обновить несуществующую задачу
PUT {{baseUrl}}/tasks/999
Content-Type: application/json

{
  "title": "Несуществующая задача",
  "status": "OPEN",
  "createdBy": {{userId}}
}

### Подсчитать активные задачи пользователя
GET {{baseUrl}}/tasks/active/count?userId={{userId}}

### Удалить задачу
DELETE {{baseUrl}}/tasks/{{createTask1.response.body.id}}

### Удалить несуществующую задачу
DELETE {{baseUrl}}/tasks/999

### Проверить, что задача удалена
GET {{baseUrl}}/tasks/{{createTask1.response.body.id}}